apiVersion: v1
kind: Secret
metadata:
  name: registry
  annotations:
    {}
  labels:
    {}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    [TROQUE PELA SUA CONFIGURACAO]9fX0=

