apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-frontend
  labels:
    app: aplicacao-frontend
spec:
  selector:
    matchLabels:
      app: aplicacao-frontend    
  replicas: 1
  template:
    metadata:
      labels:
        app: aplicacao-frontend
    spec:
      containers:
        - name: aplicacao-frontend
          image: {{IMAGE_PARAM}}
          envFrom:
            - configMapRef:
                name: aplicacao-frontend-configmap
            - secretRef:
                name: aplicacao-frontend-secret
      imagePullSecrets:
      - name: registry

